### ISSUE TITLE
Wrong Timestamp error

### ISSUE THREAD

**Issue by br-at-d** [snovvcrash/usbrip#14]
I always get "CRITICAL] Wrong timestamp format found in "/var/log/syslog"" when running this tool on an existing syslog file

**Comment by snovvcrash** [comment]
Please, show an example of how your `/var/log/syslog` looks like (some random line).

**Comment by br-at-d** [comment]
I  discovered this when doing your HTB challenge

Nov  9 09:56:57 kali kernel: [ 2556.806748] usb 2-1: Product: 180038A2EF71F12960D35319D3EF153
Nov  9 09:56:57 kali kernel: [ 2556.806749] usb 2-1: Manufacturer: 1336BA657773B419D3EE799258FF7
Nov  9 09:56:57 kali kernel: [ 2556.806750] usb 2-1: SerialNumber: 139DADB1430077E5C67ED03
Nov  9 09:56:57 kali kernel: [ 2556.806751] usb-storage 2-1:1.0: USB Mass Storage device detected
Nov  9 09:56:57 kali kernel: [ 2556.806752] scsi host3: usb-storage 2-1:1.0
Nov  9 09:57:23 kali kernel: [ 2556.806753] usb 2-1: USB disconnect, device number 5

**Comment by snovvcrash** [comment]
Take a look at #7 and the new [requirement](https://github.com/snovvcrash/usbrip#system-log-structure) for the syslog structure. Closing as a duplicate.
