### ISSUE TITLE
Error with usbrip

### ISSUE THREAD

**Issue by LexusMinder** [snovvcrash/usbrip#16]
Can you help me? I have the follwing error output when I try to run the tool, I had tried all version but all version show the same output . 

`File "/usr/local/bin/usbrip", line 10, in <module>
    sys.exit(main())`
`File "/usr/local/lib/python3.7/dist-packages/usbrip/__main__.py", line 104, in main
    repres=repres`
`File "/usr/local/lib/python3.7/dist-packages/usbrip/lib/core/usbevents.py", line 147, in open_dump
    events_to_show = _filter_events(events_dumped, sieve)`
`File "/usr/local/lib/python3.7/dist-packages/usbrip/lib/core/usbevents.py", line 489, in _filter_events
    return [events_to_show[SIZE-i] for i in range(sieve['number'], 0, -1)]`
`File "/usr/local/lib/python3.7/dist-packages/usbrip/lib/core/usbevents.py", line 489, in <listcomp>
    return [events_to_show[SIZE-i] for i in range(sieve['number'], 0, -1)]`

**Comment by snovvcrash** [comment]
Please provide the command you use to run usbrip. Also the error output that you are giving is not complete, may I have a screenshot, please?

**Comment by LexusMinder** [comment]
Of coruse the screen is below if you need more info I can provide it. 


![Captura1](https://user-images.githubusercontent.com/25314705/64479624-46c6db80-d17f-11e9-976c-2eb711814c19.JPG)

**Comment by snovvcrash** [comment]
I see. I'm sorry, at first I didn't understand that you're writing with regard to my HTB challenge. I don't want to spoil the task so I will only say that the tool is fine (even the latest version is able to solve it in one line). The thing is you are doing it the wrong way. Try harder :smiling_imp:
