### ISSUE TITLE
Request for syslog samples with an important num of USB entries

### ISSUE THREAD

**Issue by Sim4n6** [snovvcrash/usbrip#18]
I was wondering if you have samples of syslog logs with an important number of USB entries.
 
I've found couple samples online but most of them contain a small number of USB entries, something like HackTheBox challenge sample, please?

**Comment by snovvcrash** [comment]
Hmm, what do you mean by syslog sample with an important number of USB entries? Do you mean such a log file which contains a huge amount of events? If yes, you could try to generate it yourself, that would be the simplest option.

**Comment by Sim4n6** [comment]
Yes, huge amount of events, definitely right, thank you
