### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by Leva7** [snovvcrash/usbrip#2]
The latest commit (97d372b) has introduced a [syntax error](https://github.com/snovvcrash/usbrip/commit/97d372bc7b245f501cb53f68a9d74733afe3d34e#diff-a9929c4206a7e5cdbaba7e4982eb4157R102) by breaking the `elif` chain with a string literal. Consider using comments instead.

**Comment by snovvcrash** [comment]
Thanks, that was just an in-the-middle-of-work commit. Fixed by now.
