### ISSUE TITLE
Allow for running without root

### ISSUE THREAD

**Issue by tomtastic** [snovvcrash/usbrip#20]
Some of us probably have access to our log files without being root,
can we change this to check for read permissions to the logfiles instead :
```
		if os.geteuid() != 0:
			sys.exit('Permission denied. Retry with sudo')
```

Maybe allow using the storage feature for non-root installations too?

**Comment by snovvcrash** [comment]
I have changed the behavior to allow non-root usage for events/history and events/open modules. For the rest of the functionality (events/genauth, events/violations and storage/* modules) I'm afraid I'll have to stick to the ugly `if os.geteuid() != 0` checks. Within these modules usbrip hardly relies on reading from (writing to) some system [paths](https://github.com/snovvcrash/usbrip#paths) and that would be a pain to change this behavior at this point. So I guess it's part of the design now =)
