### ISSUE TITLE
WTF?? error

### ISSUE THREAD

**Issue by ZevSuk** [snovvcrash/usbrip#21]
my Ubuntu16

![usbrip](https://user-images.githubusercontent.com/26931732/84387843-4cfd5300-abfc-11ea-9297-33f4491025ce.png)

**Comment by snovvcrash** [comment]
You're trying to install the package for Python 3.5. As it is stated in the [Dependencies](https://github.com/snovvcrash/usbrip#deb-packages) section Python 3.6 or newer is required.
