### ISSUE TITLE
Error in running from terminal

### ISSUE THREAD

**Issue by urwithajit9** [snovvcrash/usbrip#5]
Traceback (most recent call last):
  File "/home/ajit/.local/bin/usbrip", line 7, in <module>
    from usbrip.__main__ import main
  File "/home/ajit/.local/lib/python3.5/site-packages/usbrip/__main__.py", line 66
    print(f'# Done as: usbrip {" ".join(sys.argv[1:])}')
                                                      ^
SyntaxError: invalid syntax

**Comment by snovvcrash** [comment]
You are using an older version of Python interpreter (3.5). As it is stated in the [Dependencies](https://github.com/snovvcrash/usbrip#deb-packages) paragraph, you should be running python3.6 or newer to use usbrip. The error that you are facing with is related to f-strings that Python <3.6 cannot work with.
Uninstall usbrip, upgrade your Python interpreter and install it again.
