### ISSUE TITLE
Parsing of syslog timestamps is broken

### ISSUE THREAD

**Issue by Jarijaas** [snovvcrash/usbrip#8]
Commit https://github.com/snovvcrash/usbrip/commit/5c6f62652b0c47e12195c2b1b6392440c11a70f2 broke parsing of syslog timestamps that are in the following format: "Nov  9 09:56:57"

**Comment by snovvcrash** [comment]
Take a look at [this issue](https://github.com/snovvcrash/usbrip/issues/7#issuecomment-520219053).
