### ISSUE TITLE
sys.exit(main())

### ISSUE THREAD

**Issue by goxy2101** [snovvcrash/usbrip#9]
Tool started from terminal with processing a syslog file with command:
usbrip events violations auth.json -f syslog
and after couple of seconds stop with errors:

[*] Started at 2019-08-12 00:43:57
[00:43:57] [INFO] Reading "syslog"
Traceback (most recent call last):
  File "/usr/local/bin/usbrip", line 10, in <module>
    sys.exit(main())
  File "/opt/usbrip/venv/lib/python3.7/site-packages/usbrip/__main__.py", line 126, in main
    uev = USBEvents(args.file)
  File "/opt/usbrip/venv/lib/python3.7/site-packages/usbrip/lib/core/usbevents.py", line 93, in __new__
    all_events = _parse_history(divided_history)
  File "/opt/usbrip/venv/lib/python3.7/site-packages/usbrip/lib/core/usbevents.py", line 343, in _parse_history
    for (date, action), logs in _sort_by_date(divided_history.items()):
  File "/opt/usbrip/venv/lib/python3.7/site-packages/usbrip/lib/core/usbevents.py", line 434, in _sort_by_date
    return sorted(unsorted_log, key=lambda i: MONTH_ENUM[i[0][0][:3]] + i[0][0][3:])
  File "/opt/usbrip/venv/lib/python3.7/site-packages/usbrip/lib/core/usbevents.py", line 434, in <lambda>
    return sorted(unsorted_log, key=lambda i: MONTH_ENUM[i[0][0][:3]] + i[0][0][3:])
KeyError: '201'
[*] Shutted down at 2019-08-12 00:44:03
[*] Time taken: 0:00:05.211522

Version: v2.1.3-3 - because of ald date/time log format data in syslog file
Python 3.7.4

Installation passed ok 

root@kali:~/Desktop/_TOOLS/USB/usbrip-3fb6103a76d2955a5cd75152b1036fa2ab44abb8# ./installers/install.sh
>>>> Creating directory: '/opt/usbrip'
>>>> Successfully created directory: '/opt/usbrip'

>>>> Creating directory: '/var/opt/usbrip/log'
>>>> Successfully created directory: '/var/opt/usbrip/log'

>>>> Creating directory: '/var/opt/usbrip/storage'
>>>> Successfully created directory: '/var/opt/usbrip/storage'

>>>> Building Python virtual environment
>>>> Successfully builded Python virtual environment

>>>> Installing usbrip
Processing /root/Desktop/Desktop/Boxes/_TOOLS/USB/usbrip-3fb6103a76d2955a5cd75152b1036fa2ab44abb8
Collecting termcolor (from usbrip==2.1.3.post3)
Collecting terminaltables (from usbrip==2.1.3.post3)
Building wheels for collected packages: usbrip
  Running setup.py bdist_wheel for usbrip ... done
  Stored in directory: /root/.cache/pip/wheels/67/21/71/a4eb3a95286cc8a05987071f2e8b22e379adc4d387f8ebe94b
Successfully built usbrip
Installing collected packages: termcolor, terminaltables, usbrip
Successfully installed termcolor-1.1.0 terminaltables-3.1.0 usbrip-2.1.3.post3
>>>> Successfully installed usbrip using PyPI dependencies

/opt/usbrip/venv/lib/python3.7/site-packages/setuptools/dist.py:475: UserWarning: Normalizing '2.1.3-3' to '2.1.3.post3'
  normalized_version,
running clean

>>>> Created symlink: '/usr/local/bin/usbrip'
>>>> Done.

**Comment by snovvcrash** [comment]
Take a look at [this issue](https://github.com/snovvcrash/usbrip/issues/7#issuecomment-520219053) and a new [requirement](https://github.com/snovvcrash/usbrip#system-log-structure) for the syslog structure.
